version: '3'
services:
  indexer:
    image: nginx:1.23.1
    volumes:
      # Serve point (browsable directory)
      - ${SERVEPOINT}:/servePoint
      # Web root
      - ./public:/var/www/html
      # Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PORT}
    links:
      - php
  php:
    image: php:7.4-fpm
    volumes:
      # Serve point (browsable directory)
      - ${SERVEPOINT}:/servePoint
      # Web root
      - ./public:/var/www/html
      # Indexer configuration
      - ./config.php:/var/www/html/indexer.config.php